jaoafa/Javajaotan2

src/main/java/com/jaoafa/javajaotan2/Main.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_GenText.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanLibrary.java, src/main/resources/external_scripts/gentext/.gitignore, src/main/resources/external_scripts/gentext/main.py
=> feat: #28 gentextコマンドの実装

src/main/java/com/jaoafa/javajaotan2/command/Cmd_GenText.java, src/main/resources/external_scripts/gentext/.gitignore, src/main/resources/external_scripts/gentext/main.py
=> feat: gentextをマルチプロセスに対応。

src/main/java/com/jaoafa/javajaotan2/event/Event_WarnUsers.java
=> fix: WarnUsers一部修正

src/main/java/com/jaoafa/javajaotan2/event/Event_NeedSupport.java
close https://github.com/jaoafa/jao-Minecraft-Server/issues/38
=> feat: #support にチャットしたユーザーに対して NeedSupport 権限を付与する

src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java
- expired_dateがnullな人がエラーになる不具合の修正
- JSONArrayのつもりがJSONObjectだったのを修正
- 2回以上リンクしている人がリンクしていない扱いになる不具合修正
=> fix: nullのエラー・リンク不具合等の修正

src/main/java/com/jaoafa/javajaotan2/tasks/Task_CheckMailVerified.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java
=> chore: PermSync, MemberOrganize, CheckMailVerifiedのデフォルトdryRunを解除 (本番動作)

src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
- fix: ISO_ZONED_DATE_TIMEからISO_LOCAL_DATE_TIMEへ変更、JSONArrayなのにJSONObjectだったバグを修正
=> fix: perm-syncのバグ修正

src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java
=> feat: GIF画像をアイコンにしている場合Nitrotanをつける

src/main/java/com/jaoafa/javajaotan2/tasks/Task_CheckMailVerified.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_SyncOtherServerPerm.java, src/main/resources/external_scripts/getguildmembers/main.py
- 出力を一時ファイルに投げた
- nullだった場合処理中断するようにした
- スレッドに名前つけた
=> fix: スレッドに名前つけたりバグ修正したりetc

src/main/java/com/jaoafa/javajaotan2/lib/SubAccount.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
=> fix: #92 サブアカウントなのにSubAccount役職がついていない場合、SubAccount役職を付与する

src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
=> feat: #111 自動キック時、generalで通知を投稿する

src/main/java/com/jaoafa/javajaotan2/event/Event_UserDedDB.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
close #110
https://github.com/jaoafa/jaoweb-docs/issues/88
=> feat: リンク自動解除時、dead_atに切断日時とdead_permに元権限を記録しておく

src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java
イベント登録時にはMain.getJDA()がNullなの忘れてた
=> fix: 運営内審議処理の修正

src/main/java/com/jaoafa/javajaotan2/command/Cmd_Search.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_SearchImg.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanCommand.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanConfig.java
=> feat: searchコマンドとsearchimgコマンドの追加

src/main/java/com/jaoafa/javajaotan2/command/Cmd_GameRole.java, src/main/java/com/jaoafa/javajaotan2/lib/Roles.java
- `/gamerole new|create|add <Name...>`: ゲームロールを新規作成
- `/gamerole color <Name> <ColorCode>`: ゲームロールの色を変更 (ゲームロール名にスペースが入る場合はダブルクォーテーションで囲む)
- `/gamerole rename <Name> <NewName>` : ゲームロール名の変更 (ゲームロール名にスペースが入る場合はダブルクォーテーションで囲む)
- `/gamerole give|join <Name>`: ゲームロールを自分に付与する
- `/gamerole take|leave <Name>`: ゲームロールを自分から剥奪する
=> feat: gameroleの作成

.github/workflows/dependencies-update.yml, pom.xml, src/main/java/com/jaoafa/javajaotan2/command/Cmd_WatchEmoji.java, src/main/java/com/jaoafa/javajaotan2/event/Event_NeedSupport.java
- pomxml-dep-update から `com.squareup.okhttp3.okhttp` を除外
- JDA、logback-classic、junit-jupiterのアップデートを実施
- 上記依存関係のアップデートに伴いコードの修正
=> feat: Update dependencies packages

src/main/java/com/jaoafa/javajaotan2/event/Event_PinReaction.java
=> fix(PinReaction): #185 📌リアクション時の条件追加

.run/Run Test.run.xml, src/main/java/com/jaoafa/javajaotan2/event/Event_Greeting.java, src/main/java/com/jaoafa/javajaotan2/lib/Channels.java
=> feat: greeting

src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
=> fix: #219 CommunityRegularへの権限復元対応

src/main/java/com/jaoafa/javajaotan2/event/Event_Greeting.java
=> fix: greetingでjaotanのメッセージが削除されてしまう不具合の修正

src/main/java/com/jaoafa/javajaotan2/event/Event_GameRole.java
=> feat: リアクションによるゲームロール付与時にDMに流すように

src/main/java/com/jaoafa/javajaotan2/lib/InviteLink.java
=> fix: 招待リンクがうまく動かない件、とりあえずデバッグコード追加。

src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java
=> fix: voteのリマインドが何度も送られる不具合の修正

src/main/java/com/jaoafa/javajaotan2/event/Event_UserDedDB.java
=> fix: 退出時記録が正常に動作していない不具合を修正

src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java
=> fix: Limited Verified対応

src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
=> fix: 60日以内にログインしていて、2か月経過通知済みの場合はリセットするように

pom.xml, src/main/java/com/jaoafa/javajaotan2/Main.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_GameRole.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_Search.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_SearchImg.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToRandJa.java, src/main/java/com/jaoafa/javajaotan2/event/Event_BugReaction.java, src/main/java/com/jaoafa/javajaotan2/event/Event_CheckNitroEmoji.java, src/main/java/com/jaoafa/javajaotan2/event/Event_GameRole.java, src/main/java/com/jaoafa/javajaotan2/event/Event_Greeting.java, src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java, src/main/java/com/jaoafa/javajaotan2/event/Event_NeedSupport.java, src/main/java/com/jaoafa/javajaotan2/event/Event_PinReaction.java, src/main/java/com/jaoafa/javajaotan2/event/Event_VCSpeechLogLink.java, src/main/java/com/jaoafa/javajaotan2/event/Event_WatchEmojis.java, src/main/java/com/jaoafa/javajaotan2/lib/GameRole.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanCommand.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanLibrary.java, src/main/java/com/jaoafa/javajaotan2/lib/SubAccount.java, src/main/java/com/jaoafa/javajaotan2/lib/Translate.java, src/main/java/com/jaoafa/javajaotan2/lib/WatchEmojis.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_SyncOtherServerPerm.java
=> feat: JDA v5.0.0-alpha.17に対応

src/main/java/com/jaoafa/javajaotan2/event/Event_Greeting.java
=> feat: #297 jao afa挨拶後に出るメッセージに13歳未満利用禁止の文言を追加

src/main/java/com/jaoafa/javajaotan2/command/Cmd_Test.java, src/main/java/com/jaoafa/javajaotan2/event/Event_UserDedDB.java, src/main/java/com/jaoafa/javajaotan2/lib/CommandArgument.java, src/main/java/com/jaoafa/javajaotan2/lib/DiscordMinecraftLink.java, src/main/java/com/jaoafa/javajaotan2/lib/MinecraftPermGroup.java, src/main/java/com/jaoafa/javajaotan2/lib/Roles.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_PermSync.java
=> refactor: 連携関連リファクタリング

src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToChaos.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_Translate.java, src/main/java/com/jaoafa/javajaotan2/lib/Translate.java
- close #303 
- close #312 
ついでに、`translate` コマンドのエイリアス `to` の追加、単一翻訳の結果表示をembed化しました。
=> feat: tochaos(alias: contorandja)の実装

src/main/java/com/jaoafa/javajaotan2/lib/DiscordMinecraftLink.java
=> fix: DiscordMinecraftLinkでMemberオブジェクトを正常に取得できない不具合修正

pom.xml, src/main/java/com/jaoafa/javajaotan2/Main.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_Akakese.java, src/main/java/com/jaoafa/javajaotan2/event/Event_BugReaction.java, src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MemberOrganize.java
https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.18
=> feat: JDA v5.0.0-alpha.18に対応

src/main/java/com/jaoafa/javajaotan2/event/Event_AntiEnEn.java
ついでに「えんえん」「ひーん」単独のメッセージの場合も対象にすることにした
=> fix: えんえん絵文字のIDが違ったっぽい

src/main/java/com/jaoafa/javajaotan2/command/Cmd_GameRole.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_UserKey.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_WatchEmoji.java, src/main/java/com/jaoafa/javajaotan2/lib/CommandAction.java, src/main/java/com/jaoafa/javajaotan2/lib/CommandArgument.java, src/test/com/jaoafa/javajaotan2/lib/CommandArgumentTest.java, src/test/com/jaoafa/javajaotan2/lib/DiscordMinecraftLinkTest.java, src/test/com/jaoafa/javajaotan2/lib/MinecraftPermGroupTest.java, src/test/com/jaoafa/javajaotan2/lib/TranslateTest.java
=> fix: 引数パース処理修正

src/main/java/com/jaoafa/javajaotan2/Main.java, src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java, src/main/java/com/jaoafa/javajaotan2/tasks/Task_MeetingVote.java
=> fix: #356 投票リマインド処理などを定期実行するように修正

.github/workflows/qodana-clone-finder.yml, .github/workflows/qodana-quality.yml, .github/workflows/release.yml, pom.xml
- https://github.com/jaoafa/Javajaotan2/pull/367
- https://github.com/jaoafa/Javajaotan2/pull/363
- https://github.com/jaoafa/Javajaotan2/pull/361
- https://github.com/jaoafa/Javajaotan2/pull/355
- https://github.com/jaoafa/Javajaotan2/pull/354
- https://github.com/jaoafa/Javajaotan2/pull/351
- https://github.com/jaoafa/Javajaotan2/pull/348
- https://github.com/jaoafa/Javajaotan2/pull/347
- https://github.com/jaoafa/Javajaotan2/pull/341
- https://github.com/jaoafa/Javajaotan2/pull/283
- https://github.com/jaoafa/Javajaotan2/pull/188
- https://github.com/jaoafa/Javajaotan2/pull/281
=> Update dependencies packages by renovate (2022-10-31)

pom.xml, src/main/java/com/jaoafa/javajaotan2/Main.java, src/main/java/com/jaoafa/javajaotan2/lib/InviteLink.java, src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanConfig.java
=> fix: サーバ管理権限がないサーバに対してInviteLinkの取得処理が動作しないように修正

src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToAr.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToArJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToChaos.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToEn.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToEnJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToHe.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToHeJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToKoJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToRandJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToSw.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToSwJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToZh.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_ToZhJa.java, src/main/java/com/jaoafa/javajaotan2/command/Cmd_Translate.java, src/main/java/com/jaoafa/javajaotan2/lib/Translate.java
=> feat: 翻訳関連のリファクタリング、翻訳元言語と翻訳先言語が同じ場合にエラーを出すように

src/main/java/com/jaoafa/javajaotan2/event/Event_MeetingVote.java
=> fix: meeting-voteのタイマ実行でエラーが出る問題の修正
